# Generated by Django 3.2 on 2021-07-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(default='https://github.com/shobhit1215', max_length=500),
        ),
    ]
